<?php 
session_start();
session_regenerate_id();
if(!isset($_SESSION['user']))      // if there is no valid session
{
    header("Location: /");
	session_write_close();
} else {
	session_write_close();
}
?>
<!--  END PHP   -->
<!--            -->
<!-- START HTML -->
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<script type='text/javascript' src='js/jquery-3.1.1.js'></script>
	<script type='text/javascript' src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<script type="text/javascript" src="js/typeahead.bundle.js"></script>
	<script type="text/javascript" src="https://use.fontawesome.com/b13b15e43b.js"></script>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">	
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans" >
	<link rel="stylesheet" href="css/style.css" rel="stylesheet" >

	<title>Technician Lookup</title>
	
	<!-- Logout Button -->
	<div id="logout-button">
		<div class="btn-group">
		  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<?php echo strtoupper($_SESSION['user']);?> <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu">
			<li><a href="logout.php">Logout</a></li>
		  </ul>
		</div>
	</div>
		
<script type='text/javascript'>


$(document).ready(function(){
	$body = $("body");	
	$(document).on({
		ajaxStart: function() { $body.addClass("loading");    },
		ajaxStop: function()  { $body.removeClass("loading"); }    
	});
	
    // Defining the local dataset
	var schools = ['Abbotsford Primary School - 1886', 
					'Aberfeldie Primary School - 4220', 
					'Ainslie Parklands Primary School - 4879', 
					'Aireys Inlet Primary School (interim name) - 5566', 
					'Airly Primary School - 4169', 
					'Aitken Creek Primary School - 5522', 
					'Alamanda K-9 College - 5528', 
					'Albanvale Primary School - 5179', 
					'Albany Rise Primary School - 5427', 
					'Albert Park College - 8889', 
					'Albert Park Primary School - 1181', 
					'Alberton Primary School - 0001', 
					'Albion North Primary School - 4855', 
					'Albion Primary School - 4265', 
					'Aldercourt Primary School - 5043', 
					'Alexandra Primary School - 0912', 
					'Alexandra Secondary College - 7505', 
					'Alfredton Primary School - 1091', 
					'Alkira Secondary College - 8874', 
					'Allansford And District Primary School - 0003', 
					'Alphington Primary School - 3599', 
					'Altona Green Primary School - 5287', 
					'Altona Meadows Primary School - 5172', 
					'Altona North Primary School - 4931', 
					'Altona P-9 College - 8857', 
					'Altona Primary School - 3923', 
					'Alvie Consolidated School - 6201', 
					'Amphitheatre Primary School - 1637', 
					'Amsleigh Park Primary School - 5428', 
					'Anakie Primary School - 1910', 
					'Andersons Creek Primary School - 5104', 
					'Anglesea Primary School - 4332', 
					'Antonio Park Primary School - 4844', 
					'Apollo Bay P-12 College - 6203', 
					'Apollo Parkways Primary School - 5184', 
					'Appin Park Primary School - 5207', 
					'Apsley Primary School - 1208', 
					'Araluen Primary School - 5021', 
					'Ararat North Primary School - 4995', 
					'Ararat Primary School - 0800', 
					'Ararat Secondary College - 8753', 
					'Ararat West Primary School - 4720', 
					'Ardeer Primary School - 4848', 
					'Ardeer South Primary School - 5064', 
					'Ardmona Primary School - 1563', 
					'Armadale Primary School - 2634', 
					'Arnolds Creek Primary School - 5557', 
					'Arthurs Creek Primary School - 1666', 
					'Ascot Vale Primary School - 2608', 
					'Ascot Vale Special School - 5109', 
					'Ascot Vale West Primary School - 4025', 
					'Ashburton Primary School - 4317', 
					'Ashby Primary School - 1492', 
					'Ashwood High School - 8743', 
					'Ashwood School - 5097', 
					'Aspendale Gardens Primary School - 5301', 
					'Aspendale Primary School - 4193', 
					'Athol Road Primary School - 5536', 
					'Auburn High School - 7526', 
					'Auburn Primary School - 2948', 
					'Auburn South Primary School - 4183', 
					'Aurora School - 5511', 
					'Austin Hospital School - 3605', 
					'Avenel Primary School - 0008', 
					'Avenues Education - 6363', 
					'Avoca Primary School - 0004', 
					'Avondale Primary School - 4812', 
					'Axedale Primary School - 1008', 
					'Bacchus Marsh College - 8777', 
					'Bacchus Marsh Primary School - 0028', 
					'Baden Powell P-9 College - 5315', 
					'Badger Creek Primary School - 3309', 
					'Baimbridge College - 8814', 
					'Bairnsdale Primary School - 0754', 
					'Bairnsdale Secondary College - 8466', 
					'Bairnsdale West Primary School - 4725', 
					'Ballam Park Primary School - 5005', 
					'Ballan Primary School - 1435', 
					'Ballarat High School - 7540', 
					'Ballarat North Primary School - 4690', 
					'Ballarat Primary School (Dana Street) - 0033', 
					'Ballarat Secondary College - 8828', 
					'Ballarat Specialist School - 4762', 
					'Balliang East Primary School - 3787', 
					'Balmoral K-12 Community College - 8872', 
					'Balnarring Primary School - 1698', 
					'Baltara School - 3552', 
					'Balwyn High School - 7550', 
					'Balwyn North Primary School - 4638', 
					'Balwyn Primary School - 1026', 
					'Bandiana Primary School - 4691', 
					'Bannockburn Prep-Year 12 School (interim name) - 8906', 
					'Bannockburn Primary School - 0932', 
					'Banyan Fields Primary School - 3613', 
					'Banyule Primary School - 4746', 
					'Baranduda Primary School - 2222', 
					'Baringa Special School - 5079', 
					'Baringhup Primary School - 1687', 
					'Barnawartha Primary School - 1489', 
					'Barwon Heads Primary School - 1574', 
					'Barwon Valley School - 5368', 
					'Bass Coast Specialist School - 8859', 
					'Bass Valley Primary School - 5195', 
					'Baxter Primary School - 3023', 
					'Bayles Regional Primary School - 5421', 
					'Bayside P-12 College - 8800', 
					'Bayside Special Developmental School - 5240', 
					'Bayswater North Primary School - 4143', 
					'Bayswater Primary School - 2163', 
					'Bayswater Secondary College - 7560', 
					'Bayswater South Primary School - 4973', 
					'Bayswater West Primary School - 5039', 
					'Beaconsfield Primary School - 3033', 
					'Beaconsfield Upper Primary School - 2560', 
					'Bealiba Primary School - 0749', 
					'Beaufort Primary School - 0060', 
					'Beaufort Secondary College - 7565', 
					'Beaumaris North Primary School - 4803', 
					'Beaumaris Primary School - 3899', 
					'Beeac Primary School - 0482', 
					'Beechworth Primary School - 1560', 
					'Beechworth Secondary College - 7575', 
					'Belgrave South Primary School - 3551', 
					'Bell Park North Primary School - 4962', 
					'Bell Primary School - 4309', 
					'Bellaire Primary School - 4873', 
					'Bellarine Secondary College - 8250', 
					'Bellbrae Primary School - 0319', 
					'Bellbridge Primary School - 5254', 
					'Belle Vue Park Primary School - 5453', 
					'Belle Vue Primary School - 4733', 
					'Belmont High School - 7585', 
					'Belmont Primary School - 0026', 
					'Belmore School - 4675', 
					'Belvedere Park Primary School - 4902', 
					'Belvoir Wodonga Special Developmental School - 5222', 
					'Benalla P-12 College - 8915', 
					'Bendigo Primary School - 0877', 
					'Bendigo Senior Secondary College - 7595', 
					'Bendigo South East 7-10 Secondary College - 7837', 
					'Bendigo Special Developmental School - 5298', 
					'Bentleigh Secondary College - 7255', 
					'Bentleigh West Primary School - 4318', 
					'Benton Junior College - 5488', 
					'Berendale School - 4928', 
					'Berwick Chase Primary School - 5503', 
					'Berwick Fields Primary School - 5305', 
					'Berwick Lodge Primary School - 5213', 
					'Berwick Primary School - 0040', 
					'Berwick Secondary College - 7603', 
					'Bethal Primary School - 5186', 
					'Bethanga Primary School - 1883', 
					'Beulah Primary School - 3109', 
					'Beverford District Primary School - 5407', 
					'Beveridge Primary School - 1476', 
					'Beverley Hills Primary School - 4813', 
					'Big Hill Primary School - 1551', 
					'Billanook Primary School - 5193', 
					'Bimbadeen Heights Primary School - 5011', 
					'Birchip P-12 School - 8832', 
					'Birmingham Primary School - 5048', 
					'Birralee Primary School - 4991', 
					'Birregurra Primary School - 0723', 
					'Bittern Primary School - 3933', 
					'Black Hill Primary School - 2043', 
					'Black Rock Primary School - 3631', 
					'Blackburn English Language School - 8747', 
					'Blackburn High School - 7610', 
					'Blackburn Lake Primary School - 4860', 
					'Blackburn Primary School - 2923', 
					'Boisdale Consolidated School - 6207', 
					'Bolinda Primary School - 1070', 
					'Bolwarra Primary School - 1324', 
					'Bona Vista Primary School - 3612', 
					'Bonbeach Primary School - 4798', 
					'Boneo Primary School - 1184', 
					'Boolarra Primary School - 2617', 
					'Boort District P-12 School - 8882', 
					'Boronia Heights Primary School - 4967', 
					'Boronia K-12 College - 8913', 
					'Boronia West Primary School - 4908', 
					'Boroondara Park Primary School - 5288', 
					'Bourchier Street Primary School Shepparton - 4742', 
					'Box Hill High School - 7635', 
					'Box Hill North Primary School - 4717', 
					'Box Hill Senior Secondary College - 7050', 
					'Brandon Park Primary School - 5038', 
					'Branxholme-Wallacedale Community School - 5377', 
					'Brauer Secondary College - 7395', 
					'Braybrook College - 7645', 
					'Brentwood Park Primary School - 5308', 
					'Brentwood Secondary College - 7647', 
					'Briagolong Primary School - 1117', 
					'Briar Hill Primary School - 4341', 
					'Bridgewater Primary School - 1097', 
					'Bright P-12 College - 0776', 
					'Brighton Beach Primary School - 2048', 
					'Brighton Primary School - 1542', 
					'Brighton Secondary College - 7650', 
					'Broadford Primary School - 1125', 
					'Broadford Secondary College - 7655', 
					'Broadmeadows Primary School - 4875', 
					'Broadmeadows Special Developmental School - 5262', 
					'Broadmeadows Valley Primary School - 5098', 
					'Broken Creek Primary School - 0862', 
					'Brookside P-9 College - 8908', 
					'Brunswick East Primary School - 3179', 
					'Brunswick North Primary School - 3585', 
					'Brunswick North West Primary School - 4399', 
					'Brunswick Secondary College - 8807', 
					'Brunswick South Primary School - 2743', 
					'Brunswick South West Primary School - 4304', 
					'Bruthen Primary School - 1141', 
					'Buangor Primary School - 2072', 
					'Buchan Primary School - 1905', 
					'Buckley Park College - 7670', 
					'Bullarto Primary School - 1288', 
					'Bulleen Heights School - 5099', 
					'Buln Buln Primary School - 2017', 
					'Bundalaguah Primary School - 5392', 
					'Bundarra Primary School - 5228', 
					'Bundoora Primary School - 4944', 
					'Bundoora Secondary College - 7874', 
					'Bungaree Primary School - 1960', 
					'Buninyong Primary School - 1270', 
					'Bunyip Primary School - 2229', 
					'Burwood East Primary School - 0454', 
					'Burwood East Special Developmental School - 5225', 
					'Burwood Heights Primary School - 4932', 
					'Buxton Primary School - 1669', 
					'Cairnlea Park Primary School - 1434', 
					'Caledonian Primary School - 5384', 
					'California Gully Primary School - 0123', 
					'Camberwell High School - 7680', 
					'Camberwell Primary School - 0888', 
					'Camberwell South Primary School - 4170', 
					'Cambridge Primary School - 5312', 
					'Camelot Rise Primary School - 5111', 
					'Camp Hill Primary School - 1976', 
					'Campbellfield Heights Primary School - 5034', 
					'Campbells Creek Primary School - 0120', 
					'Camperdown College - 6259', 
					'Canadian Lead Primary School - 5383', 
					'Cann River P-12 College - 3920', 
					'Canterbury Girls Secondary College - 7690', 
					'Canterbury Primary School - 3572', 
					'Cape Clear Primary School - 1484', 
					'Cardinia Primary School - 3689', 
					'Cardross Primary School - 4263', 
					'Carisbrook Primary School - 1030', 
					'Carlisle River Primary School - 3497', 
					'Carlton Gardens Primary School - 2605', 
					'Carlton North Primary School - 1252', 
					'Carlton Primary School - 4980', 
					'Carnegie Primary School - 2897', 
					'Carranballac P-9 College - 5486', 
					'Carraragarmungee Primary School - 1704', 
					'Carrington Primary School - 5426', 
					'Carrum Downs Secondary College - 8423', 
					'Carrum Primary School - 3385', 
					'Carwatha College P-12 - 5435', 
					'Casterton Primary School - 2058', 
					'Casterton Secondary College - 7695', 
					'Castlemaine North Primary School - 2051', 
					'Castlemaine Primary School - 0119', 
					'Castlemaine Secondary College - 8824', 
					'Caulfield Junior College - 3820', 
					'Caulfield Primary School - 5489', 
					'Caulfield South Primary School - 4315', 
					'Cavendish Primary School - 0116', 
					'Ceres Primary School - 1602', 
					'Chaffey Secondary College - 7250', 
					'Chalcot Lodge Primary School - 5231', 
					'Chandler Park Primary School - 5533', 
					'Charles La Trobe P-12 College - 8890', 
					'Charlton College - 8830', 
					'Chatham Primary School - 4314', 
					'Chelsea Heights Primary School - 3341', 
					'Chelsea Primary School - 3729', 
					'Cheltenham East Primary School - 4754', 
					'Cheltenham Primary School - 0084', 
					'Cheltenham Secondary College - 7720', 
					'Chewton Primary School - 1054', 
					'Chiltern Primary School - 0327', 
					'Chilwell Primary School - 2061', 
					'Chirnside Park Primary School - 5194', 
					'Christmas Hills Primary School - 1362', 
					'Chum Creek Primary School - 3279', 
					'Churchill North Primary School - 5117', 
					'Churchill Primary School - 4970', 
					'Clarinda Primary School - 3336', 
					'Clarkefield Primary School - 3035', 
					'Clayton North Primary School - 0734', 
					'Clayton South Primary School - 4384', 
					'Clifton Creek Primary School - 3684', 
					'Clifton Hill Primary School - 1360', 
					'Clifton Springs Primary School - 5280', 
					'Clunes Primary School - 1552', 
					'Clyde Primary School - 3664', 
					'Coatesville Primary School - 4712', 
					'Cobains Primary School - 4387', 
					'Cobden Primary School - 0864', 
					'Cobden Technical School - 7088', 
					'Cobram and District Specialist School - 5147', 
					'Cobram Primary School - 6209', 
					'Cobram Secondary College - 7725', 
					'Coburg High School - 8849', 
					'Coburg North Primary School - 4543', 
					'Coburg Primary School - 0484', 
					'Coburg Special Developmental School - 5261', 
					'Coburg West Primary School - 3941', 
					'Coburn Primary School - 5090', 
					'Cockatoo Primary School - 3535', 
					'Cohuna Consolidated School - 6211', 
					'Cohuna Secondary College - 7735', 
					'Coimadai Primary School - 0716', 
					'Colac Primary School - 0117', 
					'Colac Secondary College - 8864', 
					'Colac South West Primary School - 4775', 
					'Colac Specialist School - 5247', 
					'Colac West Primary School - 4064', 
					'Colbinabbin Primary School - 3936', 
					'Coldstream Primary School - 5127', 
					'Coleraine Primary School - 2118', 
					'Collingwood College - 6212', 
					'Collingwood English Language School - 8748', 
					'Commercial Road Primary School - Morwell - 2136', 
					'Concongella Primary School - 1136', 
					'Concord School - 5027', 
					'Congupna Primary School - 2563', 
					'Coolaroo South Primary School - 5554', 
					'Copperfield College - 8799', 
					'Coral Park Primary School - 5292', 
					'Corryong College - 8843', 
					'Courtenay Gardens Primary School - 5371', 
					'Cowes Primary School - 1282', 
					'Cowwarr Primary School - 1967', 
					'Craigieburn Primary School - 4770', 
					'Craigieburn Secondary College - 8705', 
					'Craigieburn South Primary School - 5243', 
					'Cranbourne Carlisle Primary School - 5510', 
					'Cranbourne East Primary School - 5518', 
					'Cranbourne East Secondary College - 8898', 
					'Cranbourne North West Primary School (Vacant Site) - 5515', 
					'Cranbourne Park Primary School - 4887', 
					'Cranbourne Primary School - 2068', 
					'Cranbourne Secondary College - 7747', 
					'Cranbourne South Primary School - 4755', 
					'Cranbourne South West Primary School (vacant site) - 5560', 
					'Cranbourne West Primary School - 5189', 
					'Creekside K-9 College - 8909', 
					'Creswick North Primary School - 2041', 
					'Creswick Primary School - 0122', 
					'Crib Point Primary School - 3080', 
					'Croxton Special School - 4679', 
					'Croydon Community School - 7757', 
					'Croydon Hills Primary School - 5255', 
					'Croydon Primary School - 2900', 
					'Croydon Special Developmental School - 5210', 
					'Crusoe 7-10 Secondary College - 7205', 
					'Cudgee Primary School - 0105', 
					'Currawa Primary School - 3907', 
					'Dallas Brooks Community Primary School - 5546', 
					'Dandenong High School - 8858', 
					'Dandenong North Primary School - 4723', 
					'Dandenong Primary School - 1403', 
					'Dandenong South Primary School - 4810', 
					'Dandenong Valley Special Developmental School - 5238', 
					'Dandenong West Primary School - 4217', 
					'Dargo Primary School - 1081', 
					'Darley Primary School - 5200', 
					'Darnum Primary School - 2319', 
					'Darraweit Guim Primary School - 0878', 
					'Dartmoor Primary School - 1035', 
					'Daylesford Primary School - 1609', 
					'Daylesford Secondary College - 7115', 
					'Deans Marsh Primary School - 1642', 
					'Debney Meadows Primary School - 5068', 
					'Dederang Primary School - 1772', 
					'Deepdene Primary School - 3680', 
					'Deer Park North Primary School - 5084', 
					'Deer Park West Primary School - 5032', 
					'Delacombe Primary School - 5201', 
					'Derinya Primary School - 4996', 
					'Derrimut Primary School - 5512', 
					'Derrinallum P-12 College - 5375', 
					'Devenish Primary School - 1764', 
					'Devon Meadows Primary School - 3924', 
					'Devon North Primary School - 2703', 
					'Dhurringile Primary School - 3944', 
					'Diamond Creek East Primary School - 5037', 
					'Diamond Creek Primary School - 1003', 
					'Diamond Valley College - 8746', 
					'Diamond Valley Special Developmental School - 5161', 
					'Diggers Rest Primary School - 2479', 
					'Dimboola Memorial Secondary College - 7770', 
					'Dimboola Primary School - 1372', 
					'Dingley Primary School - 4257', 
					'Dinjerra Primary School - 5450', 
					'Distance Education Centre Victoria - 6261', 
					'Dixons Creek Primary School - 1585', 
					'Don Valley Primary School - 3956', 
					'Donald High School - 7775', 
					'Donald Primary School - 1465', 
					'Donburn Primary School - 5019', 
					'Doncaster Gardens Primary School - 5454', 
					'Doncaster Primary School - 0197', 
					'Doncaster Secondary College - 7776', 
					'Donvale Primary School - 4961', 
					'Dookie Primary School - 1527', 
					'Doreen Primary School - 0945', 
					'Dorset Primary School - 5132', 
					'Doveton College - 8905', 
					'Dromana Primary School - 0184', 
					'Dromana Secondary College - 7122', 
					'Drouin Primary School - 1924', 
					'Drouin Secondary College - 7785', 
					'Drouin South Primary School - 2313', 
					'Drouin West Primary School - 1417', 
					'Drummond Primary School - 1848', 
					'Drysdale Primary School - 1645', 
					'Dunkeld Consolidated School - 6215', 
					'Dunolly Primary School - 1582', 
					'Eagle Point Primary School - 3215', 
					'Eaglehawk North Primary School - 1428', 
					'Eaglehawk Primary School - 0210', 
					'Eaglehawk Secondary College - 7790', 
					'East Bentleigh Primary School - 4837', 
					'East Doncaster Secondary College - 7773', 
					'East Gippsland Specialist School - 5490', 
					'East Loddon P-12 College - 6217', 
					'Eastbourne Primary School - 5133', 
					'Eastern Ranges School - 5309', 
					'Eastwood Primary School - 4702', 
					'Echuca College - 8855', 
					'Echuca East Primary School - 2667', 
					'Echuca Primary School - 0208', 
					'Echuca South Primary School - 4994', 
					'Echuca Specialist School - 5299', 
					'Echuca West Primary School - 3916', 
					'Edenhope College - 5432', 
					'Edi Upper Primary School - 1422', 
					'Edithvale Primary School - 3790', 
					'Eildon Primary School - 3931', 
					'Elisabeth Murdoch College - 8722', 
					'Elliminyt Primary School - 2028', 
					'Ellinbank Primary School - 2189', 
					'Elmhurst Primary School - 0959', 
					'Elmore Primary School - 1515', 
					'Elphinstone Primary School - 0220', 
					'Elsternwick Primary School - 2870', 
					'Eltham East Primary School - 4897', 
					'Eltham High School - 7805', 
					'Eltham North Primary School - 4212', 
					'Eltham Primary School - 0209', 
					'Elwood College - 7810', 
					'Elwood Primary School - 3942', 
					'Emerald Primary School - 3381', 
					'Emerald Secondary College - 8707', 
					'Emerson School - 4918', 
					'EP Monitoring School - 9800', 
					'Eppalock Primary School - 1788', 
					'Epping Primary School - 5551', 
					'Epping Secondary College - 7813', 
					'Epping Views Primary School - 5513', 
					'Epsom Primary School - 2367', 
					'Eskdale Primary School - 2318', 
					'Essendon East Keilor District College - 8806', 
					'Essendon North Primary School - 4015', 
					'Essendon Primary School - 0483', 
					'Essex Heights Primary School - 4903', 
					'Euroa Primary School - 1706', 
					'Euroa Secondary College - 7820', 
					'Everton Primary School - 5399', 
					'Example Primary School - 1234', 
					'Exford Primary School - 3423', 
					'Fairfield Primary School - 2711', 
					'Fairhills High School - 7823', 
					'Fairhills Primary School - 4906', 
					'Falls Creek Primary School - 5067', 
					'Fawkner Primary School - 3590', 
					'Featherbrook P-9 College - 8899', 
					'Ferntree Gully North Primary School - 4718', 
					'Ferny Creek Primary School - 3228', 
					'Findon Primary School - 5244', 
					'Fish Creek and District Primary School - 3028', 
					'Fitzroy High School - 8742', 
					'Fitzroy North Primary School - 1490', 
					'Fitzroy Primary School - 0450', 
					'Fleetwood Primary School - 4407', 
					'Flemington Primary School - 0250', 
					'Flowerdale Primary School - 3098', 
					'Footscray City College - 8836', 
					'Footscray City Primary School - 1912', 
					'Footscray North Primary School - 4160', 
					'Footscray Primary School - 0253', 
					'Footscray West Primary School - 3890', 
					'Forest Hill College - 8724', 
					'Forest Street Primary School - 4936', 
					'Forrest Primary School - 2708', 
					'Foster Primary School - 6221', 
					'Fountain Gate Primary School - 5072', 
					'Fountain Gate Secondary College - 8870', 
					'Frankston East Primary School - 4682', 
					'Frankston Heights Primary School - 4815', 
					'Frankston High School - 7850', 
					'Frankston Primary School - 1464', 
					'Frankston Special Developmental School - 5143', 
					'Furlong Park School For Deaf Children - 5214', 
					'Fyans Park Primary School - 4919', 
					'Gardenvale Primary School - 3897', 
					'Garfield Primary School - 2724', 
					'Geelong East Primary School - 0541', 
					'Geelong High School - 7855', 
					'Geelong South Primary School - 2143', 
					'Gembrook Primary School - 2506', 
					'George Street Primary School - Hamilton - 4777', 
					'Gilmore College For Girls - 7841', 
					'Girgarre Primary School - 3971', 
					'Gisborne Primary School - 0262', 
					'Gisborne Secondary College - 7857', 
					'Gladesville Primary School - 5066', 
					'Gladstone Park Primary School - 5007', 
					'Gladstone Park Secondary College - 7858', 
					'Gladstone Views Primary School - 5093', 
					'Gladysdale Primary School - 3982', 
					'Glen Eira College - 8704', 
					'Glen Huntly Primary School - 3703', 
					'Glen Iris Primary School - 1148', 
					'Glen Katherine Primary School - 5260', 
					'Glen Park Primary School - 1135', 
					'Glen Waverley Primary School - 5425', 
					'Glen Waverley Secondary College - 8808', 
					'Glen Waverley South Primary School - 5436', 
					'Glenallen School - 4968', 
					'Glendal Primary School - 5010', 
					'Gleneagles Secondary College - 8869', 
					'Glenferrie Primary School - 1508', 
					'Glengala/Sunshine West Primary School - 5050', 
					'Glengarry Primary School - 2888', 
					'Glenrowan Primary School - 1742', 
					'Glenroy Central Primary School - 5542', 
					'Glenroy Secondary College - 8893', 
					'Glenroy Specialist School - 4915', 
					'Glenroy West Primary School - 4809', 
					'Golden Square Primary School - 5531', 
					'Goonawarra Primary School - 5248', 
					'Goongerah Tubbut P–8 College - 5547', 
					'Goornong Primary School - 1598', 
					'Gordon Primary School - 0755', 
					'Gormandale And District Primary School - 5442', 
					'Goroke P-12 College - 6223', 
					'Gowrie Street Primary School Shepparton - 4657', 
					'Grahamvale Primary School - 3696', 
					'Grasmere Primary School - 5381', 
					'Great Ryrie Primary School - 5478', 
					'Great Western Primary School - 0860', 
					'Greenhills Primary School - 4893', 
					'Greensborough Primary School - 2062', 
					'Greensborough Secondary College - 8750', 
					'Greenvale Primary School - 0890', 
					'Greta Valley Primary School - 5398', 
					'Grey Street Primary School (Traralgon) - 3584', 
					'Greythorn Primary School - 4694', 
					'Grovedale College - 7183', 
					'Grovedale Primary School - 0283', 
					'Grovedale West Primary School - 5076', 
					'Gruyere Primary School - 2956', 
					'Guildford Primary School - 0264', 
					'Gunbower Primary School - 2231', 
					'Guthridge Primary School - 4853', 
					'Guthrie Street Primary School Shepparton - 5020', 
					'Haddon Primary School - 1076', 
					'Hallam Primary School - 0244', 
					'Hallam Senior Secondary College - 8868', 
					'Halls Gap Primary School - 3058', 
					'Hamilton (Gray Street) Primary School - 0295', 
					'Hamilton North Primary School - 2035', 
					'Hamilton Special Developmental School - 5283', 
					'Hamlyn Banks Primary School - 4804', 
					'Hampden Specialist School - 5276', 
					'Hampton Park Primary School - 4062', 
					'Hampton Park Secondary College - 8709', 
					'Hampton Primary School - 3754', 
					'Harcourt Valley Primary School - 5404', 
					'Harkaway Primary School - 1697', 
					'Harrietville Primary School - 0843', 
					'Harrisfield Primary School - 4730', 
					'Harston Primary School - 1458', 
					'Hartwell Primary School - 4055', 
					'Harvest Home Primary School - 5500', 
					'Hastings Primary School - 1098', 
					'Hawkesdale P12 College - 5434', 
					'Hawthorn West Primary School - 0293', 
					'Hazel Glen College - 5552', 
					'Hazel Glen Secondary College (interim name) - 8902', 
					'Hazelwood North Primary School - 2382', 
					'Healesville High School - 7900', 
					'Healesville Primary School - 0849', 
					'Heany Park Primary School - 5345', 
					'Heathcote Primary School - 0300', 
					'Heather Grove Primary School (vacant site) - 5558', 
					'Heatherhill Primary School - 4802', 
					'Heatherwood School - 4871', 
					'Heathmont College - 8816', 
					'Heathmont East Primary School - 4819', 
					'Heidelberg Primary School - 0294', 
					'Hepburn Primary School - 0767', 
					'Herne Hill Primary School - 4681', 
					'Hesket Primary School - 1004', 
					'Heyfield Primary School - 1108', 
					'Heywood Consolidated School - 6225', 
					'Heywood District Secondary College - 7910', 
					'Highlands Primary School - 3440', 
					'Highton Primary School - 0304', 
					'Highvale Primary School - 4986', 
					'Highvale Secondary College - 7918', 
					'Hillsmeade Primary School - 5482', 
					'Hoddles Creek Primary School - 2541', 
					'Hopetoun P-12 College - 8904', 
					'Hoppers Crossing Secondary College - 8710', 
					'Horsham College - 8818', 
					'Horsham Primary School - 5548', 
					'Horsham Special School - 5273', 
					'Horsham West and Haven Primary School - 4697', 
					'Hughesdale Primary School - 4176', 
					'Hume Central Secondary College - 8862', 
					'Hume Valley School - 4950', 
					'Huntingdale Primary School - 4716', 
					'Huntly Primary School - 0306', 
					'Hurstbridge Primary School - 3939', 
					'Inglewood Primary School - 1052', 
					'Invergordon Primary School - 4896', 
					'Inverleigh Primary School - 1147', 
					'Inverloch Primary School - 2776', 
					'Invermay Primary School - 0882', 
					'Iramoo Primary School - 5152', 
					'Irymple Primary School - 3174', 
					'Irymple Secondary College - 7198', 
					'Irymple South Primary School - 3702', 
					'Ivanhoe East Primary School - 4386', 
					'Ivanhoe Primary School - 2436', 
					'Jacana School for Autism - 5555', 
					'Jackson School - 4979', 
					'James Cook Primary School - 5136', 
					'Jamieson Primary School - 0814', 
					'Jells Park Primary School - 5176', 
					'Jennings Street School - 5215', 
					'Jeparit Primary School - 2988', 
					'Jindivick Primary School - 1951', 
					'John Fawkner Secondary College - 8894', 
					'John Monash Science School - 8856', 
					'Kalianna Special School - 4728', 
					'Kalinda Primary School - 5121', 
					'Kallista Primary School - 3993', 
					'Kambrya College - 8421', 
					'Kananook Primary School - 5418', 
					'Kangaroo Flat Primary School - 0981', 
					'Kangaroo Ground Primary School - 2105', 
					'Kaniva College - 8842', 
					'Karingal Heights Primary School - 5053', 
					'Karingal Primary School - 4922', 
					'Karoo Primary School - 5295', 
					'Katamatite Primary School - 2069', 
					'Katandra School - 4846', 
					'Katandra West Primary School - 4401', 
					'Katunga Primary School - 4689', 
					'Katunga South Primary School - 2269', 
					'Keilor Downs Secondary College - 8715', 
					'Keilor Heights Primary School - 4877', 
					'Keilor Primary School - 1578', 
					'Keilor Views Primary School - 5539', 
					'Kennington Primary School - 3686', 
					'Kensington Community High School - 7947', 
					'Kensington Primary School - 2374', 
					'Kent Park Primary School - 5082', 
					'Kerang Primary School - 1410', 
					'Kerang South Primary School - 4949', 
					'Kerang Technical High School - 7945', 
					'Kerrimuir Primary School - 4816', 
					'Kew East Primary School - 3161', 
					'Kew High School - 7950', 
					'Kew Primary School - 1075', 
					'Keysborough Primary School - 5534', 
					'Keysborough Secondary College - 8867', 
					'Kialla Central Primary School - 1366', 
					'Kialla West Primary School - 1727', 
					'Kiewa Valley Primary School - 6229', 
					'Kilberry Valley Primary School - 5350', 
					'Killara Primary School - 5352', 
					'Kilmore Primary School - 1568', 
					'Kilsyth Primary School - 3645', 
					'Kinglake Primary School - 2188', 
					'Kinglake West Primary School - 3255', 
					'Kings Park Primary School - 5236', 
					'Kingsbury Primary School - 4845', 
					'Kingsley Park Primary School - 5135', 
					'Kingston Heath Primary School - 5101', 
					'Kingsville Primary School - 3988', 
					'Kingswood Primary School - 5106', 
					'Kismet Park Primary School - 5180', 
					'Knox Central Primary School - 5429', 
					'Knox Gardens Primary School - 5234', 
					'Knox Park Primary School - 4990', 
					'Kongwak Primary School - 3323', 
					'Koo Wee Rup Primary School - 2629', 
					'Koo Wee Rup Secondary College - 7955', 
					'Koondrook Primary School - 2265', 
					'Koonung Secondary College - 7954', 
					'Koorlong Primary School - 3470', 
					'Koroit And District Primary School - 0618', 
					'Kororoit Creek Primary School - 5499', 
					'Korumburra Primary School - 3077', 
					'Korumburra Secondary College - 7960', 
					'Kunyung Primary School - 5182', 
					'Kurnai College - 8716', 
					'Kurunjang Primary School - 5256', 
					'Kurunjang Secondary College - 8718', 
					'Kyabram P-12 College - 7965', 
					'Kyneton Primary School - 0343', 
					'Kyneton Secondary College - 7970', 
					'Labertouche Primary School - 2471', 
					'Laburnum Primary School - 4863', 
					'Laharum Primary School - 2805', 
					'Lake Boga Primary School - 3278', 
					'Lake Bolac College - 0854', 
					'Lake Charm Primary School - 2122', 
					'Lakes Entrance Primary School - 2672', 
					'Lakes Entrance Secondary College - 8720', 
					'Lakeview Senior College - 8910', 
					'Lal Lal Primary School - 0863', 
					'Lalor East Primary School - 4976', 
					'Lalor Gardens Primary School - 5532', 
					'Lalor North Primary School - 5035', 
					'Lalor North Secondary College - 7986', 
					'Lalor Primary School - 4709', 
					'Lalor Secondary College - 7985', 
					'Lancaster Primary School - 1814', 
					'Lancefield Primary School - 0707', 
					'Landsborough Primary School - 1862', 
					'Lang Lang Primary School - 2899', 
					'Langley Primary School - 1275', 
					'Langwarrin Park Primary School - 5257', 
					'Langwarrin Primary School - 3531', 
					'Lara Lake Primary School - 0769', 
					'Lara Primary School - 4885', 
					'Lara Secondary College - 8841', 
					'Lardner and District Primary School - 5393', 
					'Latrobe Special Developmental School - 5221', 
					'Launching Place Primary School - 2599', 
					'Laurimar Primary School - 5497', 
					'Lavers Hill P-12 College - 6231', 
					'Laverton P-12 College - 8861', 
					'Le Page Primary School - 5422', 
					'Leitchville Primary School - 2087', 
					'Lemnos Primary School - 4269', 
					'Leongatha Primary School - 2981', 
					'Leongatha Secondary College - 8745', 
					'Leopold Primary School - 1146', 
					'Lethbridge Primary School - 1386', 
					'Lightning Reef Primary School - 5541', 
					'Lilydale Heights College - 7219', 
					'Lilydale High School - 7995', 
					'Lilydale Primary School - 0876', 
					'Lilydale West Primary School - 5057', 
					'Lindenow Primary School - 1120', 
					'Lindenow South Primary School - 2963', 
					'Linton Primary School - 0880', 
					'Lismore Primary School - 1293', 
					'Little Bendigo Primary School - 2093', 
					'Little River Primary School - 1961', 
					'Livingstone Primary School - 5113', 
					'Lloyd Street Primary School - 4139', 
					'Loch Primary School - 2912', 
					'Loch Sport Primary School - 5245', 
					'Lockington Consolidated School - 6233', 
					'Lockwood Primary School - 0744', 
					'Lockwood South Primary School - 0385', 
					'Longford Primary School - 1694', 
					'Longwarry Primary School - 2505', 
					'Longwood Primary School - 2707', 
					'Lorne - Aireys Inlet P-12 College - 2162', 
					'Lorne P-12 College (interim name) - 7997', 
					'Lowanna College - 8821', 
					'Lower Plenty Primary School - 1295', 
					'Lucknow Primary School - 1231', 
					'Lynall Hall Community School - 8003', 
					'Lynbrook Primary School - 5494', 
					'Lyndale Greens Primary School - 5535', 
					'Lyndale Secondary College - 8000', 
					'Lyndhurst Primary School - 5521', 
					'Lyndhurst Secondary College - 7108', 
					'Lysterfield Primary School - 1866', 
					'Macarthur Primary School - 1571', 
					'Macarthur Street Primary School - 2022', 
					'Macclesfield Primary School - 3620', 
					'Macedon Primary School - 1660', 
					'Mackellar Primary School - 5297', 
					'Macleod College - 6242', 
					'MacRobertson Girls High School - 8135', 
					'Maffra Primary School - 0861', 
					'Maffra Secondary College - 8005', 
					'Magpie Primary School - 2271', 
					'Mahogany Rise Primary School - 4939', 
					'Maiden Gully Primary School - 1592', 
					'Maldon Primary School - 1254', 
					'Mallacoota P-12 College - 3515', 
					'Malmsbury Primary School - 1408', 
					'Malvern Central School - 1604', 
					'Malvern Primary School - 2586', 
					'Malvern Valley Primary School - 4669', 
					'Manangatang P-12 College - 6235', 
					'Manchester Primary School - 5009', 
					'Mandama Primary School - 5185', 
					'Manifold Heights Primary School - 4224', 
					'Manor Lakes P-12 College - 8848', 
					'Manorvale Primary School - 5091', 
					'Mansfield Primary School - 1112', 
					'Mansfield Secondary College - 8010', 
					'Maramba Primary School - 5293', 
					'Maribyrnong Secondary College - 8015', 
					'Marlborough Primary School - 5045', 
					'Marlo Primary School - 3433', 
					'Marnebek School Cranbourne - 5464', 
					'Marnoo Primary School - 1554', 
					'Marong Primary School - 0400', 
					'Maroona Primary School - 1943', 
					'Maryborough Education Centre - 8845', 
					'Marysville Primary School - 1273', 
					'Matthew Flinders Girls Secondary College - 8022', 
					'McClelland Secondary College - 8835', 
					'McGuire College - 7331', 
					'Mckinnon Primary School - 4366', 
					'Mckinnon Secondary College - 8125', 
					'Meadow Heights Primary School - 5227', 
					'Meadowglen Primary School - 5286', 
					'Meadows Primary School - 5524', 
					'Meerlieu Primary School - 2535', 
					'Melba Secondary College - 8912', 
					'Melbourne Girls College - 8819', 
					'Melbourne High School - 8025', 
					'Melrose Primary School - 5141', 
					'Melton Primary School - 0430', 
					'Melton Secondary College - 8027', 
					'Melton South Primary School - 3717', 
					'Melton Specialist School - 5162', 
					'Melton West Primary School - 5036', 
					'Mentone Girls Secondary College - 8030', 
					'Mentone Park Primary School - 4955', 
					'Mentone Primary School - 2950', 
					'Menzies Creek Primary School - 2457', 
					'Merbein P-10 College - 8886', 
					'Meredith Primary School - 1420', 
					'Merino Consolidated School - 6237', 
					'Mernda Central P-12 College - 8897', 
					'Mernda Central Prep - Year 12 School (vacant site) - 8897', 
					'Mernda Park Primary School - 5525', 
					'Mernda Primary School - 0488', 
					'Merri Creek Primary School - 3110', 
					'Merriang Special Developmental School - 5284', 
					'Merrigum Primary School - 1874', 
					'Merrijig Primary School - 1379', 
					'Merrivale Primary School - 4215', 
					'Metung Primary School - 3050', 
					'Mickleham Primary School - 1051', 
					'Middle Indigo Primary School - 1115', 
					'Middle Kinglake Primary School - 3315', 
					'Middle Park Primary School - 2815', 
					'Milawa Primary School - 0737', 
					'Mildura Primary School - 2915', 
					'Mildura Senior College - 8045', 
					'Mildura South Primary School - 4389', 
					'Mildura Specialist School - 5251', 
					'Mildura West Primary School - 3983', 
					'Milgate Primary School - 5212', 
					'Mill Park Heights Primary School - 5325', 
					'Mill Park Primary School - 5160', 
					'Mill Park Secondary College - 8775', 
					'Millwarra Primary School - 5441', 
					'Miners Rest Primary School - 1739', 
					'Minyip Primary School - 2167', 
					'Mirboo North Primary School - 2383', 
					'Mirboo North Secondary College - 8050', 
					'Mitcham Primary School - 2904', 
					'Mitta Mitta Primary School - 0887', 
					'Moe (Albert Street) Primary School - 2142', 
					'Moe (South Street) Primary School - 4662', 
					'Moe Primary School - 4740', 
					'Monash Special Developmental School - 5151', 
					'Monbulk College - 8065', 
					'Monbulk Primary School - 3265', 
					'Monmia Primary School - 5336', 
					'Mont Albert Primary School - 3943', 
					'Montague Continuing Education Centre - 2784', 
					'Monterey Secondary College - 8809', 
					'Montmorency Primary School - 4112', 
					'Montmorency Secondary College - 8068', 
					'Montmorency South Primary School - 4925', 
					'Montpellier Primary School - 4972', 
					'Montrose Primary School - 2259', 
					'Moolap Primary School - 1911', 
					'Moomba Park Primary School - 4876', 
					'Moonambel Primary School - 1683', 
					'Moonee Ponds Primary School - 3987', 
					'Moonee Ponds West Primary School - 2901', 
					'Moorabbin Primary School - 1111', 
					'Moorooduc Primary School - 2327', 
					'Mooroolbark College - 8071', 
					'Mooroolbark East Primary School - 5059', 
					'Mooroopna North Primary School - 1612', 
					'Mooroopna Park Primary School - 5088', 
					'Mooroopna Primary School - 1432', 
					'Mooroopna Secondary College - 8073', 
					'Morang South Primary School - 1975', 
					'Mordialloc Beach Primary School - 0846', 
					'Mordialloc College - 8075', 
					'Moreland Primary School - 2837', 
					'Moriac Primary School - 4117', 
					'Mornington Park Primary School - 5040', 
					'Mornington Primary School - 2033', 
					'Mornington Secondary College - 8804', 
					'Mornington Special Developmental School - 5239', 
					'Mortlake P-12 College - 5376', 
					'Morwell Central Primary School - 5568', 
					'Morwell Park Primary School - 4975', 
					'Morwell Primary School - 4692', 
					'Mossfiel Primary School - 5002', 
					'Mossgiel Park Primary School - 5205', 
					'Mount Alexander 7-12 College - 7763', 
					'Mount Beauty Primary School - 4644', 
					'Mount Beauty Secondary College - 8100', 
					'Mount Blowhard Primary School - 2037', 
					'Mount Clear College - 7267', 
					'Mount Clear Primary School - 0427', 
					'Mount Dandenong Primary School - 3284', 
					'Mount Duneed Regional Primary School - 5380', 
					'Mount Egerton Primary School - 1918', 
					'Mount Eliza North Primary School - 5140', 
					'Mount Eliza Primary School - 1368', 
					'Mount Eliza Secondary College - 8102', 
					'Mount Erin Secondary College - 7028', 
					'Mount Evelyn Primary School - 3642', 
					'Mount Macedon Primary School - 0415', 
					'Mount Martha Primary School - 5171', 
					'Mount Pleasant Primary School - 1436', 
					'Mount Pleasant Road Nunawading Primary School - 4808', 
					'Mount Ridley P-12 College - 8853', 
					'Mount View Primary School - 4923', 
					'Mount Waverley Heights Primary School - 4832', 
					'Mount Waverley North Primary School - 5430', 
					'Mount Waverley Primary School - 3432', 
					'Mount Waverley Secondary College - 8105', 
					'Mountain Gate Primary School - 4905', 
					'Movelle Primary School - 5139', 
					'Moyhu Primary School - 1335', 
					'Moyston Primary School - 1263', 
					'Mt Helen Primary School (vacant Site) - 5484', 
					'Mulgrave Primary School - 2172', 
					'Mullauna Secondary College - 8744', 
					'Mullum Primary School - 4886', 
					'Murchison Primary School - 1126', 
					'Murrabit Group School - 3859', 
					'Murrayville Community College - 5433', 
					'Murrumbeena Primary School - 3449', 
					'Murtoa College - 1549', 
					'Myrniong Primary School - 0487', 
					'Myrrhee Primary School - 2677', 
					'Myrtleford P-12 College - 8873', 
					'Nagambie Primary School - 1104', 
					'Nambrok Denison Primary School - 5395', 
					'Nangiloc Colignan and District Primary School - 5402', 
					'Nanneella Estate Primary School - 3708', 
					'Napoleons Primary School - 1072', 
					'Nar Nar Goon Primary School - 2248', 
					'Naranga Special School - 5080', 
					'Narracan Primary School - 2295', 
					'Narrawong District Primary School - 5382', 
					'Narre Warren North Primary School - 1901', 
					'Narre Warren South P-12 College - 8839', 
					'Nathalia Primary School - 2060', 
					'Nathalia Secondary College - 8140', 
					'Natimuk Primary School - 1548', 
					'Natte Yallock Primary School - 1347', 
					'Navarre Primary School - 1330', 
					'Neerim District Rural Primary School - 5394', 
					'Neerim District Secondary College - 8145', 
					'Neerim South Primary School - 2432', 
					'Nelson Park School - 4768', 
					'Nepean Special School - 4290', 
					'New Gisborne Primary School - 0467', 
					'Newborough East Primary School - 4670', 
					'Newborough Primary School - 4650', 
					'Newbury Primary School - 5545', 
					'Newcomb Park Primary School - 5444', 
					'Newcomb Secondary College - 8151', 
					'Newham Primary School - 1913', 
					'Newhaven Primary School - 3053', 
					'Newlands Primary School - 4646', 
					'Newlyn Primary School - 0453', 
					'Newmerella Primary School - 2930', 
					'Newport Gardens Primary School - 4665', 
					'Newport Lakes Primary School - 0113', 
					'Newstead Primary School - 0452', 
					'Newtown Primary School - 1887', 
					'Nhill College - 8833', 
					'Nichols Point Primary School - 3163', 
					'Nicholson Primary School - 1716', 
					'Niddrie Primary School - 5410', 
					'Nilma Primary School - 2712', 
					'Noble Park English Language School - 8749', 
					'Noble Park Primary School - 3675', 
					'Noble Park Secondary College - 8813', 
					'Noojee Primary School - 4098', 
					'Noorat Primary School - 1178', 
					'Noorinbee Primary School - 3372', 
					'Norris Bank Primary School - 3618', 
					'North Geelong Secondary College - 7856', 
					'North Melbourne Primary School - 1402', 
					'Northcote High School - 8180', 
					'Northcote Primary School - 1401', 
					'Northern Bay P-12 College - 8901', 
					'Northern College of the Arts and Technology - 7300', 
					'Northern School For Autism - 5219', 
					'Norwood Secondary College - 8185', 
					'Nossal High School - 8865', 
					'Nowa Nowa Primary School - 3738', 
					'Nullawarre and District Primary School - 1652', 
					'Nullawil Primary School - 3301', 
					'Numurkah Primary School - 2134', 
					'Numurkah Secondary College - 8190', 
					'Nungurner Primary School - 4226', 
					'Nyah District Primary School - 5456', 
					'Nyora Primary School - 3401', 
					'Oak Park Primary School - 4721', 
					'Oakleigh Primary School - 1601', 
					'Oakleigh South Primary School - 4823', 
					'Oakwood School - 8337', 
					'Oatlands Primary School - 5363', 
					'Oberon High School - 8210', 
					'Oberon Primary School - 4735', 
					'Oberon South Primary School - 4983', 
					'Ocean Grove Primary School - 3100', 
					'Officer Primary School - 2742', 
					'Officer Secondary College (interim name) - 8907', 
					'Officer Specialist School - 5550', 
					'Old Orchard Primary School - 4715', 
					'Olinda Primary School - 3494', 
					'Omeo Primary School - 0831', 
					'Orbost North Primary School - 4767', 
					'Orbost Primary School - 2744', 
					'Orbost Secondary College - 8215', 
					'Orchard Grove Primary School - 5285', 
					'Ormond Primary School - 3074', 
					'Orrvale Primary School - 3805', 
					'Osborne Primary School - 2655', 
					'Osbornes Flat Primary School - 1463', 
					'Outdoor School - 7618', 
					'Ouyen P-12 College - 8220', 
					'Overport Primary School - 4780', 
					'Oxley Primary School - 1399', 
					'Pakenham Consolidated School - 6243', 
					'Pakenham Hills Primary School - 5370', 
					'Pakenham Lakeside Primary School - 5504', 
					'Pakenham Secondary College - 8223', 
					'Pakenham South West Primary School (vacant site) - 5561', 
					'Pakenham Springs Primary School - 5507', 
					'Panmure Primary School - 1079', 
					'Panton Hill Primary School - 1134', 
					'Park Orchards Primary School - 4854', 
					'Park Ridge Primary School - 5281', 
					'Parkdale Primary School - 4171', 
					'Parkdale Secondary College - 8225', 
					'Parkhill Primary School - 5416', 
					'Parkmore Primary School - 4881', 
					'Parktone Primary School - 4843', 
					'Parkville College - 8916', 
					'Parkwood Green Primary School - 5480', 
					'Pascoe Vale Girls Secondary College - 8227', 
					'Pascoe Vale North Primary School - 4731', 
					'Pascoe Vale Primary School - 3081', 
					'Pascoe Vale South Primary School - 4704', 
					'Patterson Lakes Primary School - 5190', 
					'Patterson River Secondary College - 8725', 
					'Paynesville Primary School - 2343', 
					'Pearcedale Primary School - 2961', 
					'Pembroke Primary School - 4937', 
					'Penders Grove Primary School - 3806', 
					'Peninsula Specialist College - 5230', 
					'Penshurst Primary School - 0486', 
					'Pentland Primary School - 5369', 
					'Peranbin Primary College - 5367', 
					'Perseverance Primary School - 3261', 
					'Peter Lalor Secondary College - 7217', 
					'Phoenix P-12 Community College - 8900', 
					'Pinewood Primary School - 4874', 
					'Pleasant Street Primary School ( Ballarat) - 0695', 
					'Plenty Parklands Primary School - 1915', 
					'Point Cook Prep - Year 9 College - 4159', 
					'Point Cook Senior Secondary College - 8847', 
					'Point Lonsdale Primary School - 3322', 
					'Pomonal Primary School - 2859', 
					'Poowong Consolidated School - 6245', 
					'Porepunkah Primary School - 1144', 
					'Port Fairy Consolidated School - 6247', 
					'Port Melbourne Primary School - 2932', 
					'Port Phillip Specialist School - 5145', 
					'Portarlington Primary School - 2455', 
					'Portland Bay School - 5282', 
					'Portland North Primary School - 1194', 
					'Portland Primary School - 0489', 
					'Portland Secondary College - 8798', 
					'Portland South Primary School - 4750', 
					'Powlett River Primary School - 5423', 
					'Preston North East Primary School - 4764', 
					'Preston Primary School - 1494', 
					'Preston South Primary School - 0824', 
					'Preston West Primary School - 3885', 
					'Princes Hill Primary School - 2955', 
					'Princes Hill Secondary College - 8245', 
					'Puckapunyal Primary School - 1855', 
					'Pyalong Primary School - 2005', 
					'Pyramid Hill College - 1712', 
					'Quambatook Group School - 2443', 
					'Quarry Hill Primary School - 1165', 
					'Queenscliff Primary School - 1190', 
					'Rainbow P-12 College (interim name) - 8256', 
					'Ranfurly Primary School - 5346', 
					'Rangebank Primary School - 5232', 
					'Rangeview Primary School - 5431', 
					'Rawson Primary School - 5389', 
					'Raywood Primary School - 1844', 
					'Red Cliffs East Primary School - 4123', 
					'Red Cliffs Primary School - 4057', 
					'Red Cliffs Secondary College - 8260', 
					'Red Hill Consolidated School - 6249', 
					'Redesdale Mia Mia Primary School - 2571', 
					'Regency Park Primary School - 5131', 
					'Research Primary School - 2959', 
					'Reservoir East Primary School - 4686', 
					'Reservoir High School - 8708', 
					'Reservoir Primary School - 3960', 
					'Reservoir Views Primary School - 5523', 
					'Reservoir West Primary School - 4711', 
					'Richmond Primary School - 5269', 
					'Richmond West Primary School - 5044', 
					'Riddells Creek Primary School - 0528', 
					'Ringwood Heights Primary School - 4911', 
					'Ringwood North Primary School - 4120', 
					'Ringwood Secondary College - 8270', 
					'Ripplebrook Primary School - 2129', 
					'Ripponlea Primary School - 4087', 
					'River Gum Primary School - 5130', 
					'Roberts McCubbin Primary School - 5419', 
					'Robinvale College (interim name) - 8276', 
					'Rochester Primary School - 0795', 
					'Rochester Secondary College - 8280', 
					'Rockbank Primary School - 0919', 
					'Rokewood Primary School - 0531', 
					'Rolling Hills Primary School - 5241', 
					'Rollins Primary School - 4867', 
					'Romsey Primary School - 0366', 
					'Rosamond Special School - 4792', 
					'Rosanna Golf Links Primary School - 4753', 
					'Rosanna Primary School - 4568', 
					'Rosebud Primary School - 2627', 
					'Rosebud Secondary College - 8290', 
					'Rosebud South Primary School (vacant Site) - 5481', 
					'Rosedale Primary School - 0770', 
					'Rosehill Secondary College - 7275', 
					'Rosewood Downs Primary School - 5087', 
					'Roslyn Primary School - 4663', 
					'Rowellyn Park Primary School - 5313', 
					'Rowville Primary School - 5000', 
					'Rowville Secondary College - 8734', 
					'Roxburgh College - 8407', 
					'Roxburgh Homestead Primary School - 5443', 
					'Roxburgh Park Primary School - 5485', 
					'Roxburgh Rise Primary School - 5493', 
					'Royal Childrens Hospital Education Institute - 5023', 
					'Rubicon Outdoor Centre - 8294', 
					'Rupanyup Primary School - 1595', 
					'Rushworth P-12 College - 6238', 
					'Ruskin Park Primary School - 4916', 
					'Rutherglen High School - 8300', 
					'Rutherglen Primary School - 0522', 
					'Rye Primary School - 1667', 
					'Sale College - 8834', 
					'Sale Primary School - 0545', 
					'Sale Specialist School - 5175', 
					'San Remo Primary School - 1369', 
					'Sandringham College - 8739', 
					'Sandringham East Primary School - 4429', 
					'Sandringham Primary School - 0267', 
					'Sassafras Primary School - 3222', 
					'Scoresby Primary School - 1028', 
					'Scoresby Secondary College - 8307', 
					'Seabrook Primary School - 5337', 
					'Seaford North Primary School - 4974', 
					'Seaford Park Primary School - 5191', 
					'Seaford Primary School - 3835', 
					'Seaholme Primary School - 4440', 
					'Seaspray Primary School - 4324', 
					'Sebastopol Primary School - 1167', 
					'Selby Primary School - 4685', 
					'Serpell Primary School - 5168', 
					'Seville Primary School - 2820', 
					'Seymour College - 8884', 
					'Shelford Primary School - 0379', 
					'Shepparton East Primary School - 1713', 
					'Shepparton High School - 8320', 
					'Sherbourne Primary School - 5013', 
					'Sherbrooke Community School - 6252', 
					'Silvan Primary School - 1801', 
					'Silverton Primary School - 5120', 
					'Simpson Primary School - 4895', 
					'Skene Street School Stawell - 5272', 
					'Skipton Primary School - 0582', 
					'Skye Primary School - 1222', 
					'Solway Primary School - 4641', 
					'Somers Primary School - 4458', 
					'Somers School Camp - 4647', 
					'Somerville Primary School - 2656', 
					'Somerville Rise Primary School - 5372', 
					'Somerville Secondary College - 8875', 
					'Sorrento Primary School - 1090', 
					'South Gippsland Secondary College - 7845', 
					'South Gippsland Specialist School - 5495', 
					'South Oakleigh Secondary College - 8801', 
					'South Yarra Primary School - 0583', 
					'Southern Autistic School - 5253', 
					'Southern Cross Primary School - 5235', 
					'Southmoor Primary School - 4910', 
					'Sovereign Hill School - 5181', 
					'Specimen Hill Primary School - 1316', 
					'Spensley Street Primary School - 3146', 
					'Spotswood Primary School - 3659', 
					'Spring Gully Primary School - 3505', 
					'Spring Parks Primary School - 5538', 
					'Springhurst Primary School - 1583', 
					'Springside P-9 College - 8911', 
					'Springvale Park Special Developmental School - 5164', 
					'Springvale Rise Primary School (interim name) - 5537', 
					'St Albans East Primary School - 4741', 
					'St Albans Heights Primary School - 4948', 
					'St Albans Meadows Primary School - 5118', 
					'St Albans North Primary School - 4811', 
					'St Albans Primary School - 2969', 
					'St Albans Secondary College - 8330', 
					'St Andrews Primary School - 0128', 
					'St Arnaud Primary School - 1646', 
					'St Arnaud Secondary College - 8335', 
					'St Georges Road Primary School Shepparton - 4666', 
					'St Helena Secondary College - 8730', 
					'St Kilda Park Primary School - 2460', 
					'St Kilda Primary School - 1479', 
					'St Leonards Primary School - 0866', 
					'Stanhope Primary School - 3937', 
					'Stanley Primary School - 0550', 
					'Staughton College - 7247', 
					'Stawell Primary School - 0502', 
					'Stawell Secondary College - 8731', 
					'Stawell West Primary School - 4934', 
					'Stevensville Primary School - 5047', 
					'Stonnington Primary School - 1896', 
					'Stratford Primary School - 0596', 
					'Strathaird Primary School - 5463', 
					'Strathewen Primary School - 3947', 
					'Strathfieldsaye Primary School - 1211', 
					'Strathmerton Primary School - 2790', 
					'Strathmore North Primary School - 4821', 
					'Strathmore Primary School - 4612', 
					'Strathmore Secondary College - 8345', 
					'Streeton Primary School - 5438', 
					'Sunbury And Macedon Ranges Specialist School - 5218', 
					'Sunbury College - 8350', 
					'Sunbury Downs Secondary College - 8723', 
					'Sunbury Heights Primary School - 5197', 
					'Sunbury Primary School - 1002', 
					'Sunbury West Primary School - 5006', 
					'Sunnycliffs Primary School - 4416', 
					'Sunshine College - 8790', 
					'Sunshine Harvester Primary School - 5526', 
					'Sunshine Heights Primary School - 4744', 
					'Sunshine North Primary School - 4745', 
					'Sunshine Primary School - 3113', 
					'Sunshine Special Developmental School - 5267', 
					'Surf Coast Secondary College - 8903', 
					'Surfside Primary School - 5354', 
					'Surrey Hills Primary School - 2778', 
					'Suzanne Cory High School - 8866', 
					'Swan Hill College - 8802', 
					'Swan Hill North Primary School - 4743', 
					'Swan Hill Primary School - 1142', 
					'Swan Hill Specialist School - 5268', 
					'Swan Reach Primary School - 1631', 
					'Swifts Creek P-12 School - 8892', 
					'Swinburne Senior Secondary College - 7366', 
					'Sydenham - Hillside Primary School - 3559', 
					'Sydney Road Community School - 8368', 
					'Syndal South Primary School - 4924', 
					'Taggerty Primary School - 2544', 
					'Talbot Primary School - 0954', 
					'Talgarno Primary School - 1954', 
					'Tallangatta Primary School - 1365', 
					'Tallangatta Secondary College - 8370', 
					'Tallangatta Valley Primary School - 2337', 
					'Tallarook Primary School - 1488', 
					'Tallygaroopna Primary School - 3067', 
					'Tambo Upper Primary School - 2216', 
					'Tanjil South Primary School - 2840', 
					'Taradale Primary School - 0614', 
					'Tarnagulla Primary School - 1023', 
					'Tarneit P-9 College - 8914', 
					'Tarneit Senior College - 8854', 
					'Tarneit West Primary School (interim Name) - 8881', 
					'Tarwin Lower Primary School - 4275', 
					'Tarwin Valley Primary School - 5420', 
					'Tate Street Primary School Geelong - 4398', 
					'Tatura Primary School - 1441', 
					'Tawonga Primary School - 2282', 
					'Taylors Hill Primary School - 5508', 
					'Taylors Lakes Primary School - 5258', 
					'Taylors Lakes Secondary College - 8787', 
					'Tecoma Primary School - 3356', 
					'Teesdale Primary School - 2065', 
					'Templestowe College - 8823', 
					'Templestowe Heights Primary School - 5004', 
					'Templestowe Park Primary School - 5129', 
					'Templestowe Valley Primary School - 4985', 
					'Templeton Primary School - 5196', 
					'Tempy Primary School - 5386', 
					'Terang College - 6236', 
					'The Alpine School - 8837', 
					'The Basin Primary School - 2329', 
					'The Grange P-12 College - 8783', 
					'The Lake Primary School - 3581', 
					'The Lakes South Morang P-9 School - 8846', 
					'The Patch Primary School - 5173', 
					'Thomas Chirnside Primary School - 5343', 
					'Thomas Mitchell Primary School - 5294', 
					'Thomastown East Primary School - 4827', 
					'Thomastown Meadows Primary School - 5134', 
					'Thomastown Primary School - 0631', 
					'Thomastown Secondary College - 8383', 
					'Thomastown West Primary School - 4999', 
					'Thoona Primary School - 2056', 
					'Thornbury High School - 8797', 
					'Thornbury Primary School - 3889', 
					'Thorpdale Primary School - 2966', 
					'Timbarra P-9 College - 5479', 
					'Timbarra Secondary College (vacant Site) - 8840', 
					'Timboon P-12 School - 6260', 
					'Timor Primary School - 1207', 
					'Tinternvale Primary School - 5075', 
					'Tobruk Street Primary School - Morwell - 4680', 
					'Tongala Primary School - 6255', 
					'Tooborac Primary School - 1225', 
					'Toolamba Primary School - 1455', 
					'Toolangi Primary School - 3237', 
					'Toolern Vale and District Primary School - 5414', 
					'Toongabbie Primary School - 0856', 
					'Toora Primary School - 2253', 
					'Tooradin Primary School - 1503', 
					'Toorak Primary School - 3016', 
					'Toorloo Arm Primary School - 3968', 
					'Tootgarook Primary School - 4661', 
					'Torquay North Primary School (interim name) - 5556', 
					'Torquay P-6 College - 3368', 
					'Trafalgar High School - 8395', 
					'Trafalgar Primary School - 2185', 
					'Traralgon (Kosciuszko Street) Primary School - 4699', 
					'Traralgon (Liddiard Road) Primary School - 4700', 
					'Traralgon (Stockdale Road) Primary School - 4652', 
					'Traralgon College - 8803', 
					'Traralgon South Primary School - 2114', 
					'Travancore School - 4465', 
					'Trawalla Primary School - 1150', 
					'Trentham District Primary School - 1588', 
					'Truganina P-9 College - 5501', 
					'Truganina South Primary School - 5498', 
					'Tucker Road Bentleigh Primary School - 4687', 
					'Tullamarine Primary School - 4852', 
					'Tulliallan Primary School - 5553', 
					'Tungamah Primary School - 2225', 
					'Tyabb Primary School - 3129', 
					'Tyabb Railway Station Primary School - 3544', 
					'Tyers Primary School - 2182', 
					'Tylden Primary School - 0621', 
					'Tyrrell College - 5403', 
					'Ultima Primary School - 3426', 
					'Undera Primary School - 1771', 
					'Underbool Primary School - 3819', 
					'University High School - 8405', 
					'University Park Primary School - 4945', 
					'Upper Ferntree Gully Primary School - 3926', 
					'Upper Plenty Primary School - 1244', 
					'Upper Sandy Creek Primary School - 3145', 
					'Upper Yarra Secondary College - 8410', 
					'Upwey High School - 8415', 
					'Upwey Primary School - 4530', 
					'Upwey South Primary School - 4894', 
					'Urquhart Park Primary School - 2103', 
					'Valkstone Primary School - 4778', 
					'Vermont Primary School - 1022', 
					'Vermont Secondary College - 8420', 
					'Vermont South Special School - 5025', 
					'Verney Road School - 5153', 
					'Victoria University Secondary College - 8891', 
					'Victorian College For The Deaf - 3774', 
					'Victorian College Of The Arts Secondary School - 7384', 
					'Victorian School Of Languages - 6359', 
					'Viewbank College - 8812', 
					'Viewbank Primary School - 4892', 
					'Waaia Yalca South Primary School - 5401', 
					'Wahgunyah Primary School - 0644', 
					'Wales Street Primary School - 3139', 
					'Wallan Primary School - 0664', 
					'Wallan Secondary College - 8791', 
					'Wallarano Primary School - 5055', 
					'Wallaroo Primary School - 5202', 
					'Wallington Primary School - 3345', 
					'Walpeup Primary School - 3747', 
					'Walwa Primary School - 2806', 
					'Wandiligong Primary School - 0275', 
					'Wandin North Primary School - 3892', 
					'Wandin Yallock Primary School - 1033', 
					'Wandong Primary School - 1277', 
					'Wanganui Park Secondary College - 8422', 
					'Wangaratta District Specialist School - 5226', 
					'Wangaratta High School - 8425', 
					'Wangaratta Primary School - 0643', 
					'Wangaratta West Primary School - 4642', 
					'Wantirna College - 8428', 
					'Wantirna Primary School - 3709', 
					'Wantirna South Primary School - 4582', 
					'Waratah Special Developmental School - 5144', 
					'Warburton Primary School - 1485', 
					'Warracknabeal Primary School - 1334', 
					'Warracknabeal Secondary College - 8430', 
					'Warracknabeal Special Developmental School - 5291', 
					'Warragul & District Specialist School - 5289', 
					'Warragul North Primary School - 4695', 
					'Warragul Primary School - 2104', 
					'Warragul Regional College - 8827', 
					'Warrandyte High School - 8437', 
					'Warrandyte Primary School - 0012', 
					'Warranwood Primary School - 3476', 
					'Warrenheip Primary School - 1591', 
					'Warringa Park School - 5165', 
					'Warrnambool College - 8811', 
					'Warrnambool East Primary School - 4773', 
					'Warrnambool Primary School - 1743', 
					'Warrnambool Special Developmental School - 5277', 
					'Warrnambool West Primary School - 0182', 
					'Watsonia Heights Primary School - 4935', 
					'Watsonia North Primary School - 4988', 
					'Watsonia Primary School - 4838', 
					'Wattle Glen Primary School - 4060', 
					'Wattle Park Primary School - 3841', 
					'Wattle View Primary School - 5012', 
					'Waubra Primary School - 0859', 
					'Waverley Meadows Primary School - 5105', 
					'Wedderburn College - 6262', 
					'Wedge Park Primary School - 5206', 
					'Weeden Heights Primary School - 5157', 
					'Weeroona College Bendigo - 7405', 
					'Wellington Secondary College - 8462', 
					'Welshpool and District Primary School - 5396', 
					'Welton Primary School - 4041', 
					'Wembley Primary School - 4788', 
					'Wendouree Primary School - 1813', 
					'Werribee Primary School - 0649', 
					'Werribee Secondary College - 8465', 
					'Werrimull P-12 School - 6257', 
					'Wesburn Primary School - 3466', 
					'Westall Primary School - 4851', 
					'Westall Secondary College - 8470', 
					'Westbreen Primary School - 4158', 
					'Western Autistic School - 5290', 
					'Western English Language School - 8838', 
					'Western Heights Secondary College - 8820', 
					'Western Port Secondary College - 7893', 
					'Westgarth Primary School - 4177', 
					'Westgrove Primary School - 5365', 
					'Westmeadows Primary School - 0982', 
					'Wheelers Hill Primary School - 5094', 
					'Wheelers Hill Secondary College - 8474', 
					'White Hills Primary School - 1916', 
					'Whitehorse Primary School - 5530', 
					'Whitfield District Primary School - 5397', 
					'Whittington Primary School - 5123', 
					'Whittlesea Primary School - 2090', 
					'Whittlesea Secondary College - 7408', 
					'Whorouly Primary School - 1373', 
					'Wilandra Rise Primary School - 5558', 
					'Willaura Primary School - 2662', 
					'William Ruthven Primary School - 5544', 
					'William Ruthven Secondary College - 8895', 
					'Williamstown High School - 8475', 
					'Williamstown North Primary School - 1409', 
					'Williamstown Primary School - 1183', 
					'Willmott Park Primary School - 5342', 
					'Willow Grove Primary School - 2520', 
					'Willowmavin Primary School - 3479', 
					'Wilmot Road Primary School Shepparton - 4943', 
					'Winchelsea Primary School - 2015', 
					'Winters Flat Primary School - 0652', 
					'Winton Primary School - 1870', 
					'Woady Yaloak Primary School - 5440', 
					'Wodonga Middle Years College - 8851', 
					'Wodonga Primary School - 0037', 
					'Wodonga Senior Secondary College - 8480', 
					'Wodonga South Primary School - 5042', 
					'Wodonga West Primary School - 4814', 
					'Wonga Park Primary School - 3241', 
					'Wonthaggi North Primary School - 3716', 
					'Wonthaggi Primary School - 3650', 
					'Wonthaggi Secondary College - 8736', 
					'Woodend Primary School - 0647', 
					'Woodford Primary School - 0648', 
					'Woodlands Primary School - 5319', 
					'Woodside Primary School - 1176', 
					'Woodville Primary School - 5049', 
					'Woolsthorpe Primary School - 0688', 
					'Woomelang Group School - 3373', 
					'Wooragee Primary School - 0653', 
					'Wooranna Park Primary School - 4989', 
					'Woori Yallock Primary School - 1259', 
					'Woorinen District Primary School - 5439', 
					'Wunghnu Primary School - 1938', 
					'Wurruk Primary School - 2518', 
					'Wycheproof P-12 College - 8831', 
					'Wyndham Central Secondary College - 7402', 
					'Wyndham Park Primary School - 5540', 
					'Wyndham Vale P-9 College (interim Name) - 8880', 
					'Wyndham Vale Primary School - 5549', 
					'Yaapeet Primary School - 3976', 
					'Yackandandah Primary School - 1103', 
					'Yallourn North Primary School - 3967', 
					'Yandoit Primary School - 0691', 
					'Yarra Glen Primary School - 0956', 
					'Yarra Hills Secondary College - 8815', 
					'Yarra Junction Primary School - 3216', 
					'Yarra Primary School - 5271', 
					'Yarra Ranges Special Developmental School - 5246', 
					'Yarra Road Primary School - 4219', 
					'Yarrabah School - 5142', 
					'Yarragon Primary School - 2178', 
					'Yarram Primary School - 0693', 
					'Yarram Secondary College - 8490', 
					'Yarraman Oaks Primary School - 4807', 
					'Yarrambat Primary School - 2054', 
					'Yarraville Special Developmental School - 5278', 
					'Yarraville West Primary School - 2832', 
					'Yarrawonga College P-12 - 8883', 
					'Yarrunga Primary School - 4761', 
					'Yea High School - 8500', 
					'Yea Primary School - 0699', 
					'Yellingbo Primary School - 4705', 
					'Yering Primary School - 1034', 
					'Yinnar Primary School - 2419', 
					'Yinnar South Primary School - 2730', 
					'Yuille Park P-8 Community College - 5520', 
					'Zeerust Primary School - 4359'];

    // Constructing the suggestion engine
    var schools = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: schools
    });
    
    // Initializing the typeahead
    $('.typeahead').typeahead({
        hint: true,
        highlight: true, /* Enable substring highlighting */
        minLength: 1 /* Specify minimum characters required for showing result */
    },
    {
        name: 'schools',
        source: schools
    });

	$('input.typeahead').bind('typeahead:selected', function(event, selected, name) {
		
		$.ajax({
           type: "POST",
           url: 'lookup.php',
           data:{school: selected},
           success:function(html) {
             //alert(html);
			 $("#st-info").html(html);
           }
		});
	});

	
});
</script>
</head>

<body>
    <div class="container" id="page-wrap">
		<div id="heading">
			<h1 class="text-center">Specialist Technician Lookup</h1>
		</div>
        <input type="text" class="typeahead form-control" placeholder="Find a school" />		
		<div id="st-parent">
			<div class="modal"><!-- Place at bottom of page --></div>
			<div id="st-info">
			</div>
		</div>
    </div>

</body>

</html>